### PR TITLE
Changes iphoneos-version-min options from 5.0 to 7.0 in configure_x86_64.sh

### PR DESCRIPTION
**Pull request by shinnya**
I fixed the issue that we couldn't complete configure_x86_64.sh. 

See my previous pull request for more detail.
https://github.com/zhm/icu-ios/pull/5

### CODE REVIEW

**Comment by shinnya** [comment]
@zhm Could you please review my change?

**Comment by shinnya** [comment]
I'm using your `icu-ios` for developing my next product, so I wish this Pull Request will be merged quickly.

**Comment by zhm** [comment]
Sorry I missed this. Thanks for the PR!

**Comment by shinnya** [comment]
Thank you!

**Pull request merged**
